version: "0.2"
ignorePaths:
  - Makefile
  - .pre-commit-config.yaml
  - "*.svg"
  - .github/workflows/*.yml
  - package.json
  - package-lock.json
  - .prettierrc.json
  - .prettierignore
dictionaryDefinitions: []
dictionaries: []
words:
  - autoincrements
  - carb
  - cmdk
  - Cramer
  - Cramer's
  - creds
  - Dedup
  - desaturated
  - Elipssis
  - Embla
  - Fage
  - frob
  - Frobenius
  - gridlines
  - harissa
  - hasn
  - IDBP
  - inbucket
  - indexeddb
  - Jeor
  - licious
  - magiclink
  - maxage
  - Mifflin
  - noeng
  - nonbinary
  - nums
  - openfoodfacts
  - pangasius
  - passwordless
  - pescatarian
  - pgcrypto
  - PGRST
  - PKCE
  - plpgsql
  - Postgrest
  - sparkline
  - summarise
  - supabase
  - TDEE
  - Topbar
  - trivago
  - Turbopack
  - Unconfigured
  - upserted
  - upserts
  - vaul
  - vercel
ignoreWords: []
import: []
